/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Interface;

import Controle.Controlador;
import Modelo.CategoriaCusto;
import Modelo.Status;
import Modelo.TipoItem;
import java.awt.Component;
import java.awt.GridLayout;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author danie
 */
public class CardEvento extends javax.swing.JPanel {
    private Controlador controlador;
    private static String nomeDoEvento = "Nome do evento:";;
    private static String preenchaInformacoes = "Preencha as informações:";


    /**
     * Creates new form CardEvento
     * @param nome
     * @param controlador
     */
    public CardEvento(String nome, Controlador controlador) {
        initComponents();
        jLabel1.setText(nome);
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));
        setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jPanel1.setLayout(new java.awt.GridLayout(2, 0, 5, 5));

        jButton1.setText("Inserir despesa adicional");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        jButton3.setText("Remover despesa adicional");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);

        jButton2.setText("Inserir item buffet");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);

        jButton4.setText("Remover item buffet");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);

        jButton5.setText("Inserir funcionário");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);

        jButton6.setText("Remover funcionário");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);

        jButton7.setText("Alterar status");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);

        jButton8.setText("Alterar despesas adicionais");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JTextField eventoField = new JTextField(15);
        eventoField.setText(jLabel1.getText());
        JTextField nomeField = new JTextField(15);
        
        JRadioButton CUSTO_FIXOButton = new JRadioButton("CUSTO_FIXO");
        CUSTO_FIXOButton.setActionCommand("CUSTO_FIXO");
        JRadioButton CUSTO_VARIAVELButton = new JRadioButton("CUSTO_VARIAVEL");
        CUSTO_VARIAVELButton.setActionCommand("CUSTO_VARIAVEL");
        
        ButtonGroup group = new ButtonGroup();
        group.add(CUSTO_FIXOButton);
        group.add(CUSTO_VARIAVELButton);
        
        JTextField descricaoField = new JTextField(15);
        JTextField custoPorPessoaField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel(nomeDoEvento));
        panel.add(eventoField);
        panel.add(new JLabel("Nome da Despesa adicional:"));
        panel.add(nomeField);
        
        panel.add(new JLabel("Categoria CUSTO_FIXO ou CUSTO_VARIAVEL:"));
        panel.add(new JLabel(""));
        panel.add(CUSTO_FIXOButton);
        panel.add(CUSTO_VARIAVELButton);
        
        panel.add(new JLabel("Descrição:"));
        panel.add(descricaoField);
        panel.add(new JLabel("Custo por pessoa:"));
        panel.add(custoPorPessoaField);
        
        

        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            preenchaInformacoes,
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeEvento = eventoField.getText();
            String nomeDespesa = nomeField.getText();
            String descricao = descricaoField.getText();
            
            if(CUSTO_FIXOButton.isSelected())
            {
                controlador.validarInputsDeRegistroDeDespesaAdicional(nomeEvento, nomeDespesa, CategoriaCusto.CUSTO_FIXO, descricao, Double.parseDouble(custoPorPessoaField.getText()));
            }
            else if(CUSTO_VARIAVELButton.isSelected())
            {
                controlador.validarInputsDeRegistroDeDespesaAdicional(nomeEvento, nomeDespesa, CategoriaCusto.CUSTO_VARIAVEL, descricao, Double.parseDouble(custoPorPessoaField.getText()));
            }
            else
            {
                this.exibirMensagemDeErro();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JTextField nomeField = new JTextField(15);
        JTextField eventoField = new JTextField(15);
        eventoField.setText(jLabel1.getText());
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Item do Buffet:"));
        panel.add(nomeField);
        panel.add(new JLabel(nomeDoEvento));
        panel.add(eventoField);

        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Remover Item do buffet",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeItemBuffet = nomeField.getText();
            String nomeEvento = eventoField.getText();
            controlador.removerItemBuffet(nomeEvento, nomeItemBuffet);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JTextField nomeField = new JTextField(15);
        JTextField eventoField = new JTextField(15);
        eventoField.setText(jLabel1.getText());
        JTextField tipoField = new JTextField(15);
        JTextField custoField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 3, 5, 5));
        panel.add(new JLabel("Nome do Item do buffet:"));
        panel.add(nomeField);
        panel.add(new JLabel(""));
        panel.add(new JLabel(nomeDoEvento));
        panel.add(eventoField);
        panel.add(new JLabel(""));
        panel.add(new JLabel("Tipo BEBIDA ou COMIDA:"));
        
        JRadioButton BEBIDAButton = new JRadioButton("BEBIDA");
        BEBIDAButton.setActionCommand("BEBIDA");
        panel.add(BEBIDAButton);
        JRadioButton COMIDAButton = new JRadioButton("COMIDA");
        COMIDAButton.setActionCommand("COMIDA");
        panel.add(COMIDAButton);
        
        panel.add(new JLabel("Custo:"));
        panel.add(custoField);
        panel.add(new JLabel(""));
        
        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Inserir Item do buffet",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeItemBuffet = nomeField.getText();
            String nomeEvento = eventoField.getText();
            if(BEBIDAButton.isSelected())
            {
                controlador.validarInputsDeRegistroDeItemDoBuffet(nomeEvento, nomeItemBuffet, TipoItem.BEBIDA, Double.parseDouble(custoField.getText()));
            }
            else if(COMIDAButton.isSelected())
            {
                controlador.validarInputsDeRegistroDeItemDoBuffet(nomeEvento, nomeItemBuffet, TipoItem.COMIDA, Double.parseDouble(custoField.getText()));
            }
            else{
                this.exibirMensagemDeErro();
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        JTextField nomeField = new JTextField(15);
        JTextField eventoField = new JTextField(15);
        eventoField.setText(jLabel1.getText());
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Item do buffet:"));
        panel.add(nomeField);
        panel.add(new JLabel(nomeDoEvento));
        panel.add(eventoField);

        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Remover Item do buffet",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeItemBuffet = nomeField.getText();
            String nomeEvento = eventoField.getText();
            controlador.removerItemBuffet(nomeEvento, nomeItemBuffet);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JTextField nomeField = new JTextField(15);
        JTextField eventoField = new JTextField(15);
        eventoField.setText(jLabel1.getText());
        JTextField cpfField = new JTextField(15);
        JTextField funcaoField = new JTextField(15);
        JTextField custoField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel(nomeDoEvento));
        panel.add(eventoField);
        panel.add(new JLabel("Nome do Funcionário:"));
        panel.add(nomeField);
        panel.add(new JLabel("CPF:"));
        panel.add(cpfField);
        panel.add(new JLabel("Função:"));
        panel.add(funcaoField);
        panel.add(new JLabel("Diaria:"));
        panel.add(custoField);
        
        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Adicionar funcionario",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );
        controlador.adicionarFuncionario(eventoField.getText(), nomeField.getText(), cpfField.getText(), funcaoField.getText(), Double.parseDouble(custoField.getText()));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        JTextField nomeField = new JTextField(15);
        JTextField eventoField = new JTextField(15);
        eventoField.setText(jLabel1.getText());
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Nome do Funcionario:"));
        panel.add(nomeField);
        panel.add(new JLabel("Nome do Evento:"));
        panel.add(eventoField);

        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Remover Funcionario",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeFuncionario = nomeField.getText();
            String nomeEvento = eventoField.getText();
            controlador.removerFuncionario(nomeEvento, nomeFuncionario);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        JTextField eventoField = new JTextField(15);
        eventoField.setText(jLabel1.getText());
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel(nomeDoEvento));
        panel.add(eventoField);
        
        
        JRadioButton EncerrarButton = new JRadioButton("Encerrar");
        EncerrarButton.setActionCommand("CUSTO_FIXO");
        JRadioButton EM_ANDAMENTOButton = new JRadioButton("Em andamento");
        EM_ANDAMENTOButton.setActionCommand("Em andamento");
        
        ButtonGroup group = new ButtonGroup();
        group.add(EncerrarButton);
        group.add(EM_ANDAMENTOButton);
        
        
        panel.add(new JLabel("Categoria CUSTO_FIXO ou CUSTO_VARIAVEL:"));
        panel.add(new JLabel(""));
        panel.add(EncerrarButton);
        panel.add(EM_ANDAMENTOButton);
     
        Component frame = null;
        
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            preenchaInformacoes,
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeEvento = eventoField.getText();
            if(EncerrarButton.isSelected())
            {
                controlador.alterarStatus(nomeEvento, Status.ENCERRADO);
            }
            else if(EM_ANDAMENTOButton.isSelected())
            {
                controlador.alterarStatus(nomeEvento, Status.EM_ANDAMENTO);
            }
            
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        JTextField eventoField = new JTextField(15);
        eventoField.setText(jLabel1.getText());
        JTextField nomeField = new JTextField(15);
        JTextField novonomeField = new JTextField(15);
        JTextField novacatField = new JTextField(15);
        JTextField novadescricaoField = new JTextField(15);
        JTextField novocustoPorPessoaField = new JTextField(15);
        JPanel panel = new JPanel(new GridLayout(0, 3, 7, 5));
        panel.add(new JLabel(nomeDoEvento));
        panel.add(eventoField);
        panel.add(new JLabel(""));
        panel.add(new JLabel("Nome da Despesa adicional:"));
        panel.add(nomeField);
        panel.add(new JLabel(""));
        panel.add(new JLabel("Novo Nome da Despesa adicional:"));
        panel.add(novonomeField);
        panel.add(new JLabel(""));
        
        panel.add(new JLabel("Categoria Custo:"));
        JRadioButton CUSTO_FIXOButton = new JRadioButton("CUSTO_FIXO");
        CUSTO_FIXOButton.setActionCommand("CUSTO_FIXO");
        panel.add(CUSTO_FIXOButton);
        JRadioButton CUSTO_VARIAVELButton = new JRadioButton("CUSTO_VARIAVEL");
        CUSTO_VARIAVELButton.setActionCommand("CUSTO_VARIAVEL");
        panel.add(CUSTO_VARIAVELButton);
        
        panel.add(new JLabel("Nova Descrição:"));
        panel.add(novadescricaoField);
        panel.add(new JLabel(""));
        panel.add(new JLabel("Novo Custo por pessoa:"));
        panel.add(novocustoPorPessoaField);
        panel.add(new JLabel(""));
        
        

        Component frame = null;
        int result = JOptionPane.showConfirmDialog(
            frame, panel,
            "Preencha as informações",
            JOptionPane.OK_CANCEL_OPTION,
            JOptionPane.PLAIN_MESSAGE
        );

        if (result == JOptionPane.OK_OPTION) {
            String nomeEvento = eventoField.getText();
            String nomeDespesa = nomeField.getText();
            String descricao = novadescricaoField.getText();
            
            
            if(CUSTO_FIXOButton.isSelected())
            {
                controlador.validarInputsDeAlteracaoDeDespesaAdicional(nomeEvento, nomeDespesa, novonomeField.getText(), CategoriaCusto.CUSTO_FIXO, descricao, Double.parseDouble(novocustoPorPessoaField.getText()));
            }
            else if(CUSTO_VARIAVELButton.isSelected())
            {
                controlador.validarInputsDeAlteracaoDeDespesaAdicional(nomeEvento, nomeDespesa, novonomeField.getText(), CategoriaCusto.CUSTO_VARIAVEL, descricao, Double.parseDouble(novocustoPorPessoaField.getText()));
            }
            else
            {
                this.exibirMensagemDeErro();
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    public String getNomEvento(){
        return jLabel1.getText();
    }
    
    public void exibirMensagemDeConfirmacao()
    {
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Operação concluída"));

        JOptionPane.showMessageDialog(null, "Operação concluída", "Aviso", 1);
    }
    
    public void exibirMensagemDeErro()
    {
        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Erro detectado"));

        JOptionPane.showMessageDialog(null, "Erro detectado", "Aviso", 0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
